// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkAttachmentParams creates a new GetNetworkAttachmentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkAttachmentParams() *GetNetworkAttachmentParams {
	return &GetNetworkAttachmentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkAttachmentParamsWithTimeout creates a new GetNetworkAttachmentParams object
// with the ability to set a timeout on a request.
func NewGetNetworkAttachmentParamsWithTimeout(timeout time.Duration) *GetNetworkAttachmentParams {
	return &GetNetworkAttachmentParams{
		timeout: timeout,
	}
}

// NewGetNetworkAttachmentParamsWithContext creates a new GetNetworkAttachmentParams object
// with the ability to set a context for a request.
func NewGetNetworkAttachmentParamsWithContext(ctx context.Context) *GetNetworkAttachmentParams {
	return &GetNetworkAttachmentParams{
		Context: ctx,
	}
}

// NewGetNetworkAttachmentParamsWithHTTPClient creates a new GetNetworkAttachmentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkAttachmentParamsWithHTTPClient(client *http.Client) *GetNetworkAttachmentParams {
	return &GetNetworkAttachmentParams{
		HTTPClient: client,
	}
}

/*
GetNetworkAttachmentParams contains all the parameters to send to the API endpoint

	for the get network attachment operation.

	Typically these are written to a http.Request.
*/
type GetNetworkAttachmentParams struct {

	/* PodName.

	   Kubernetes pod name for which to query the network attachment
	*/
	PodName string

	/* PodNamespace.

	   Kubernetes pod namespace for which to query the network attachment
	*/
	PodNamespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network attachment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkAttachmentParams) WithDefaults() *GetNetworkAttachmentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network attachment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkAttachmentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network attachment params
func (o *GetNetworkAttachmentParams) WithTimeout(timeout time.Duration) *GetNetworkAttachmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network attachment params
func (o *GetNetworkAttachmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network attachment params
func (o *GetNetworkAttachmentParams) WithContext(ctx context.Context) *GetNetworkAttachmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network attachment params
func (o *GetNetworkAttachmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network attachment params
func (o *GetNetworkAttachmentParams) WithHTTPClient(client *http.Client) *GetNetworkAttachmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network attachment params
func (o *GetNetworkAttachmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPodName adds the podName to the get network attachment params
func (o *GetNetworkAttachmentParams) WithPodName(podName string) *GetNetworkAttachmentParams {
	o.SetPodName(podName)
	return o
}

// SetPodName adds the podName to the get network attachment params
func (o *GetNetworkAttachmentParams) SetPodName(podName string) {
	o.PodName = podName
}

// WithPodNamespace adds the podNamespace to the get network attachment params
func (o *GetNetworkAttachmentParams) WithPodNamespace(podNamespace string) *GetNetworkAttachmentParams {
	o.SetPodNamespace(podNamespace)
	return o
}

// SetPodNamespace adds the podNamespace to the get network attachment params
func (o *GetNetworkAttachmentParams) SetPodNamespace(podNamespace string) {
	o.PodNamespace = podNamespace
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkAttachmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param pod-name
	qrPodName := o.PodName
	qPodName := qrPodName
	if qPodName != "" {

		if err := r.SetQueryParam("pod-name", qPodName); err != nil {
			return err
		}
	}

	// query param pod-namespace
	qrPodNamespace := o.PodNamespace
	qPodNamespace := qrPodNamespace
	if qPodNamespace != "" {

		if err := r.SetQueryParam("pod-namespace", qPodNamespace); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
