// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCiliumSRv6VRFs implements CiliumSRv6VRFInterface
type FakeCiliumSRv6VRFs struct {
	Fake *FakeCiliumV2alpha1
}

var ciliumsrv6vrfsResource = v2alpha1.SchemeGroupVersion.WithResource("ciliumsrv6vrfs")

var ciliumsrv6vrfsKind = v2alpha1.SchemeGroupVersion.WithKind("CiliumSRv6VRF")

// Get takes name of the ciliumSRv6VRF, and returns the corresponding ciliumSRv6VRF object, and an error if there is any.
func (c *FakeCiliumSRv6VRFs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumSRv6VRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(ciliumsrv6vrfsResource, name), &v2alpha1.CiliumSRv6VRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6VRF), err
}

// List takes label and field selectors, and returns the list of CiliumSRv6VRFs that match those selectors.
func (c *FakeCiliumSRv6VRFs) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumSRv6VRFList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(ciliumsrv6vrfsResource, ciliumsrv6vrfsKind, opts), &v2alpha1.CiliumSRv6VRFList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.CiliumSRv6VRFList{ListMeta: obj.(*v2alpha1.CiliumSRv6VRFList).ListMeta}
	for _, item := range obj.(*v2alpha1.CiliumSRv6VRFList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ciliumSRv6VRFs.
func (c *FakeCiliumSRv6VRFs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(ciliumsrv6vrfsResource, opts))
}

// Create takes the representation of a ciliumSRv6VRF and creates it.  Returns the server's representation of the ciliumSRv6VRF, and an error, if there is any.
func (c *FakeCiliumSRv6VRFs) Create(ctx context.Context, ciliumSRv6VRF *v2alpha1.CiliumSRv6VRF, opts v1.CreateOptions) (result *v2alpha1.CiliumSRv6VRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(ciliumsrv6vrfsResource, ciliumSRv6VRF), &v2alpha1.CiliumSRv6VRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6VRF), err
}

// Update takes the representation of a ciliumSRv6VRF and updates it. Returns the server's representation of the ciliumSRv6VRF, and an error, if there is any.
func (c *FakeCiliumSRv6VRFs) Update(ctx context.Context, ciliumSRv6VRF *v2alpha1.CiliumSRv6VRF, opts v1.UpdateOptions) (result *v2alpha1.CiliumSRv6VRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(ciliumsrv6vrfsResource, ciliumSRv6VRF), &v2alpha1.CiliumSRv6VRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6VRF), err
}

// Delete takes name of the ciliumSRv6VRF and deletes it. Returns an error if one occurs.
func (c *FakeCiliumSRv6VRFs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(ciliumsrv6vrfsResource, name, opts), &v2alpha1.CiliumSRv6VRF{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCiliumSRv6VRFs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(ciliumsrv6vrfsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.CiliumSRv6VRFList{})
	return err
}

// Patch applies the patch and returns the patched ciliumSRv6VRF.
func (c *FakeCiliumSRv6VRFs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumSRv6VRF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(ciliumsrv6vrfsResource, name, pt, data, subresources...), &v2alpha1.CiliumSRv6VRF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6VRF), err
}
