// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCiliumSRv6EgressPolicies implements CiliumSRv6EgressPolicyInterface
type FakeCiliumSRv6EgressPolicies struct {
	Fake *FakeCiliumV2alpha1
}

var ciliumsrv6egresspoliciesResource = v2alpha1.SchemeGroupVersion.WithResource("ciliumsrv6egresspolicies")

var ciliumsrv6egresspoliciesKind = v2alpha1.SchemeGroupVersion.WithKind("CiliumSRv6EgressPolicy")

// Get takes name of the ciliumSRv6EgressPolicy, and returns the corresponding ciliumSRv6EgressPolicy object, and an error if there is any.
func (c *FakeCiliumSRv6EgressPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumSRv6EgressPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(ciliumsrv6egresspoliciesResource, name), &v2alpha1.CiliumSRv6EgressPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6EgressPolicy), err
}

// List takes label and field selectors, and returns the list of CiliumSRv6EgressPolicies that match those selectors.
func (c *FakeCiliumSRv6EgressPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumSRv6EgressPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(ciliumsrv6egresspoliciesResource, ciliumsrv6egresspoliciesKind, opts), &v2alpha1.CiliumSRv6EgressPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.CiliumSRv6EgressPolicyList{ListMeta: obj.(*v2alpha1.CiliumSRv6EgressPolicyList).ListMeta}
	for _, item := range obj.(*v2alpha1.CiliumSRv6EgressPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ciliumSRv6EgressPolicies.
func (c *FakeCiliumSRv6EgressPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(ciliumsrv6egresspoliciesResource, opts))
}

// Create takes the representation of a ciliumSRv6EgressPolicy and creates it.  Returns the server's representation of the ciliumSRv6EgressPolicy, and an error, if there is any.
func (c *FakeCiliumSRv6EgressPolicies) Create(ctx context.Context, ciliumSRv6EgressPolicy *v2alpha1.CiliumSRv6EgressPolicy, opts v1.CreateOptions) (result *v2alpha1.CiliumSRv6EgressPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(ciliumsrv6egresspoliciesResource, ciliumSRv6EgressPolicy), &v2alpha1.CiliumSRv6EgressPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6EgressPolicy), err
}

// Update takes the representation of a ciliumSRv6EgressPolicy and updates it. Returns the server's representation of the ciliumSRv6EgressPolicy, and an error, if there is any.
func (c *FakeCiliumSRv6EgressPolicies) Update(ctx context.Context, ciliumSRv6EgressPolicy *v2alpha1.CiliumSRv6EgressPolicy, opts v1.UpdateOptions) (result *v2alpha1.CiliumSRv6EgressPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(ciliumsrv6egresspoliciesResource, ciliumSRv6EgressPolicy), &v2alpha1.CiliumSRv6EgressPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6EgressPolicy), err
}

// Delete takes name of the ciliumSRv6EgressPolicy and deletes it. Returns an error if one occurs.
func (c *FakeCiliumSRv6EgressPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(ciliumsrv6egresspoliciesResource, name, opts), &v2alpha1.CiliumSRv6EgressPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCiliumSRv6EgressPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(ciliumsrv6egresspoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.CiliumSRv6EgressPolicyList{})
	return err
}

// Patch applies the patch and returns the patched ciliumSRv6EgressPolicy.
func (c *FakeCiliumSRv6EgressPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumSRv6EgressPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(ciliumsrv6egresspoliciesResource, name, pt, data, subresources...), &v2alpha1.CiliumSRv6EgressPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumSRv6EgressPolicy), err
}
