//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepcopy-gen. DO NOT EDIT.

package srv6

import (
	net "net"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRF) DeepCopyInto(out *VRF) {
	*out = *in
	out.id = in.id
	if in.AllocatedSID != nil {
		in, out := &in.AllocatedSID, &out.AllocatedSID
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	if in.rules != nil {
		in, out := &in.rules, &out.rules
		*out = make([]VRFRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRF.
func (in *VRF) DeepCopy() *VRF {
	if in == nil {
		return nil
	}
	out := new(VRF)
	in.DeepCopyInto(out)
	return out
}
