apiVersion: isovalent.com/v1alpha1
kind: IsovalentPodNetwork
metadata:
  name: default
spec:
  ipam:
    mode: multi-pool
    pool:
      name: default
---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentPodNetwork
metadata:
  name: secondary-network
spec:
  ipam:
    mode: multi-pool
    pool:
      name: secondary-pool
  routes:
  - destination: 192.168.0.0/16
    gateway: 192.168.0.1
