// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIsovalentPodNetworks implements IsovalentPodNetworkInterface
type FakeIsovalentPodNetworks struct {
	Fake *FakeIsovalentV1alpha1
}

var isovalentpodnetworksResource = v1alpha1.SchemeGroupVersion.WithResource("isovalentpodnetworks")

var isovalentpodnetworksKind = v1alpha1.SchemeGroupVersion.WithKind("IsovalentPodNetwork")

// Get takes name of the isovalentPodNetwork, and returns the corresponding isovalentPodNetwork object, and an error if there is any.
func (c *FakeIsovalentPodNetworks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentPodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(isovalentpodnetworksResource, name), &v1alpha1.IsovalentPodNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentPodNetwork), err
}

// List takes label and field selectors, and returns the list of IsovalentPodNetworks that match those selectors.
func (c *FakeIsovalentPodNetworks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentPodNetworkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(isovalentpodnetworksResource, isovalentpodnetworksKind, opts), &v1alpha1.IsovalentPodNetworkList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IsovalentPodNetworkList{ListMeta: obj.(*v1alpha1.IsovalentPodNetworkList).ListMeta}
	for _, item := range obj.(*v1alpha1.IsovalentPodNetworkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested isovalentPodNetworks.
func (c *FakeIsovalentPodNetworks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(isovalentpodnetworksResource, opts))
}

// Create takes the representation of a isovalentPodNetwork and creates it.  Returns the server's representation of the isovalentPodNetwork, and an error, if there is any.
func (c *FakeIsovalentPodNetworks) Create(ctx context.Context, isovalentPodNetwork *v1alpha1.IsovalentPodNetwork, opts v1.CreateOptions) (result *v1alpha1.IsovalentPodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(isovalentpodnetworksResource, isovalentPodNetwork), &v1alpha1.IsovalentPodNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentPodNetwork), err
}

// Update takes the representation of a isovalentPodNetwork and updates it. Returns the server's representation of the isovalentPodNetwork, and an error, if there is any.
func (c *FakeIsovalentPodNetworks) Update(ctx context.Context, isovalentPodNetwork *v1alpha1.IsovalentPodNetwork, opts v1.UpdateOptions) (result *v1alpha1.IsovalentPodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(isovalentpodnetworksResource, isovalentPodNetwork), &v1alpha1.IsovalentPodNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentPodNetwork), err
}

// Delete takes name of the isovalentPodNetwork and deletes it. Returns an error if one occurs.
func (c *FakeIsovalentPodNetworks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(isovalentpodnetworksResource, name, opts), &v1alpha1.IsovalentPodNetwork{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIsovalentPodNetworks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(isovalentpodnetworksResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IsovalentPodNetworkList{})
	return err
}

// Patch applies the patch and returns the patched isovalentPodNetwork.
func (c *FakeIsovalentPodNetworks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentPodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(isovalentpodnetworksResource, name, pt, data, subresources...), &v1alpha1.IsovalentPodNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentPodNetwork), err
}
