// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIsovalentSRv6LocatorPools implements IsovalentSRv6LocatorPoolInterface
type FakeIsovalentSRv6LocatorPools struct {
	Fake *FakeIsovalentV1alpha1
}

var isovalentsrv6locatorpoolsResource = v1alpha1.SchemeGroupVersion.WithResource("isovalentsrv6locatorpools")

var isovalentsrv6locatorpoolsKind = v1alpha1.SchemeGroupVersion.WithKind("IsovalentSRv6LocatorPool")

// Get takes name of the isovalentSRv6LocatorPool, and returns the corresponding isovalentSRv6LocatorPool object, and an error if there is any.
func (c *FakeIsovalentSRv6LocatorPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(isovalentsrv6locatorpoolsResource, name), &v1alpha1.IsovalentSRv6LocatorPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentSRv6LocatorPool), err
}

// List takes label and field selectors, and returns the list of IsovalentSRv6LocatorPools that match those selectors.
func (c *FakeIsovalentSRv6LocatorPools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentSRv6LocatorPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(isovalentsrv6locatorpoolsResource, isovalentsrv6locatorpoolsKind, opts), &v1alpha1.IsovalentSRv6LocatorPoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IsovalentSRv6LocatorPoolList{ListMeta: obj.(*v1alpha1.IsovalentSRv6LocatorPoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.IsovalentSRv6LocatorPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested isovalentSRv6LocatorPools.
func (c *FakeIsovalentSRv6LocatorPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(isovalentsrv6locatorpoolsResource, opts))
}

// Create takes the representation of a isovalentSRv6LocatorPool and creates it.  Returns the server's representation of the isovalentSRv6LocatorPool, and an error, if there is any.
func (c *FakeIsovalentSRv6LocatorPools) Create(ctx context.Context, isovalentSRv6LocatorPool *v1alpha1.IsovalentSRv6LocatorPool, opts v1.CreateOptions) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(isovalentsrv6locatorpoolsResource, isovalentSRv6LocatorPool), &v1alpha1.IsovalentSRv6LocatorPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentSRv6LocatorPool), err
}

// Update takes the representation of a isovalentSRv6LocatorPool and updates it. Returns the server's representation of the isovalentSRv6LocatorPool, and an error, if there is any.
func (c *FakeIsovalentSRv6LocatorPools) Update(ctx context.Context, isovalentSRv6LocatorPool *v1alpha1.IsovalentSRv6LocatorPool, opts v1.UpdateOptions) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(isovalentsrv6locatorpoolsResource, isovalentSRv6LocatorPool), &v1alpha1.IsovalentSRv6LocatorPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentSRv6LocatorPool), err
}

// Delete takes name of the isovalentSRv6LocatorPool and deletes it. Returns an error if one occurs.
func (c *FakeIsovalentSRv6LocatorPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(isovalentsrv6locatorpoolsResource, name, opts), &v1alpha1.IsovalentSRv6LocatorPool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIsovalentSRv6LocatorPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(isovalentsrv6locatorpoolsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IsovalentSRv6LocatorPoolList{})
	return err
}

// Patch applies the patch and returns the patched isovalentSRv6LocatorPool.
func (c *FakeIsovalentSRv6LocatorPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(isovalentsrv6locatorpoolsResource, name, pt, data, subresources...), &v1alpha1.IsovalentSRv6LocatorPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentSRv6LocatorPool), err
}
