// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIsovalentEgressGatewayPolicies implements IsovalentEgressGatewayPolicyInterface
type FakeIsovalentEgressGatewayPolicies struct {
	Fake *FakeIsovalentV1
}

var isovalentegressgatewaypoliciesResource = v1.SchemeGroupVersion.WithResource("isovalentegressgatewaypolicies")

var isovalentegressgatewaypoliciesKind = v1.SchemeGroupVersion.WithKind("IsovalentEgressGatewayPolicy")

// Get takes name of the isovalentEgressGatewayPolicy, and returns the corresponding isovalentEgressGatewayPolicy object, and an error if there is any.
func (c *FakeIsovalentEgressGatewayPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(isovalentegressgatewaypoliciesResource, name), &v1.IsovalentEgressGatewayPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IsovalentEgressGatewayPolicy), err
}

// List takes label and field selectors, and returns the list of IsovalentEgressGatewayPolicies that match those selectors.
func (c *FakeIsovalentEgressGatewayPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.IsovalentEgressGatewayPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(isovalentegressgatewaypoliciesResource, isovalentegressgatewaypoliciesKind, opts), &v1.IsovalentEgressGatewayPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.IsovalentEgressGatewayPolicyList{ListMeta: obj.(*v1.IsovalentEgressGatewayPolicyList).ListMeta}
	for _, item := range obj.(*v1.IsovalentEgressGatewayPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested isovalentEgressGatewayPolicies.
func (c *FakeIsovalentEgressGatewayPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(isovalentegressgatewaypoliciesResource, opts))
}

// Create takes the representation of a isovalentEgressGatewayPolicy and creates it.  Returns the server's representation of the isovalentEgressGatewayPolicy, and an error, if there is any.
func (c *FakeIsovalentEgressGatewayPolicies) Create(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.CreateOptions) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(isovalentegressgatewaypoliciesResource, isovalentEgressGatewayPolicy), &v1.IsovalentEgressGatewayPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IsovalentEgressGatewayPolicy), err
}

// Update takes the representation of a isovalentEgressGatewayPolicy and updates it. Returns the server's representation of the isovalentEgressGatewayPolicy, and an error, if there is any.
func (c *FakeIsovalentEgressGatewayPolicies) Update(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.UpdateOptions) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(isovalentegressgatewaypoliciesResource, isovalentEgressGatewayPolicy), &v1.IsovalentEgressGatewayPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IsovalentEgressGatewayPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIsovalentEgressGatewayPolicies) UpdateStatus(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.UpdateOptions) (*v1.IsovalentEgressGatewayPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(isovalentegressgatewaypoliciesResource, "status", isovalentEgressGatewayPolicy), &v1.IsovalentEgressGatewayPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IsovalentEgressGatewayPolicy), err
}

// Delete takes name of the isovalentEgressGatewayPolicy and deletes it. Returns an error if one occurs.
func (c *FakeIsovalentEgressGatewayPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(isovalentegressgatewaypoliciesResource, name, opts), &v1.IsovalentEgressGatewayPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIsovalentEgressGatewayPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(isovalentegressgatewaypoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.IsovalentEgressGatewayPolicyList{})
	return err
}

// Patch applies the patch and returns the patched isovalentEgressGatewayPolicy.
func (c *FakeIsovalentEgressGatewayPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(isovalentegressgatewaypoliciesResource, name, pt, data, subresources...), &v1.IsovalentEgressGatewayPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IsovalentEgressGatewayPolicy), err
}
