// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentSRv6SIDManagersGetter has a method to return a IsovalentSRv6SIDManagerInterface.
// A group's client should implement this interface.
type IsovalentSRv6SIDManagersGetter interface {
	IsovalentSRv6SIDManagers() IsovalentSRv6SIDManagerInterface
}

// IsovalentSRv6SIDManagerInterface has methods to work with IsovalentSRv6SIDManager resources.
type IsovalentSRv6SIDManagerInterface interface {
	Create(ctx context.Context, isovalentSRv6SIDManager *v1alpha1.IsovalentSRv6SIDManager, opts v1.CreateOptions) (*v1alpha1.IsovalentSRv6SIDManager, error)
	Update(ctx context.Context, isovalentSRv6SIDManager *v1alpha1.IsovalentSRv6SIDManager, opts v1.UpdateOptions) (*v1alpha1.IsovalentSRv6SIDManager, error)
	UpdateStatus(ctx context.Context, isovalentSRv6SIDManager *v1alpha1.IsovalentSRv6SIDManager, opts v1.UpdateOptions) (*v1alpha1.IsovalentSRv6SIDManager, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentSRv6SIDManager, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentSRv6SIDManagerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentSRv6SIDManager, err error)
	IsovalentSRv6SIDManagerExpansion
}

// isovalentSRv6SIDManagers implements IsovalentSRv6SIDManagerInterface
type isovalentSRv6SIDManagers struct {
	client rest.Interface
}

// newIsovalentSRv6SIDManagers returns a IsovalentSRv6SIDManagers
func newIsovalentSRv6SIDManagers(c *IsovalentV1alpha1Client) *isovalentSRv6SIDManagers {
	return &isovalentSRv6SIDManagers{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentSRv6SIDManager, and returns the corresponding isovalentSRv6SIDManager object, and an error if there is any.
func (c *isovalentSRv6SIDManagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentSRv6SIDManager, err error) {
	result = &v1alpha1.IsovalentSRv6SIDManager{}
	err = c.client.Get().
		Resource("isovalentsrv6sidmanagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentSRv6SIDManagers that match those selectors.
func (c *isovalentSRv6SIDManagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentSRv6SIDManagerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentSRv6SIDManagerList{}
	err = c.client.Get().
		Resource("isovalentsrv6sidmanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentSRv6SIDManagers.
func (c *isovalentSRv6SIDManagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentsrv6sidmanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentSRv6SIDManager and creates it.  Returns the server's representation of the isovalentSRv6SIDManager, and an error, if there is any.
func (c *isovalentSRv6SIDManagers) Create(ctx context.Context, isovalentSRv6SIDManager *v1alpha1.IsovalentSRv6SIDManager, opts v1.CreateOptions) (result *v1alpha1.IsovalentSRv6SIDManager, err error) {
	result = &v1alpha1.IsovalentSRv6SIDManager{}
	err = c.client.Post().
		Resource("isovalentsrv6sidmanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentSRv6SIDManager).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentSRv6SIDManager and updates it. Returns the server's representation of the isovalentSRv6SIDManager, and an error, if there is any.
func (c *isovalentSRv6SIDManagers) Update(ctx context.Context, isovalentSRv6SIDManager *v1alpha1.IsovalentSRv6SIDManager, opts v1.UpdateOptions) (result *v1alpha1.IsovalentSRv6SIDManager, err error) {
	result = &v1alpha1.IsovalentSRv6SIDManager{}
	err = c.client.Put().
		Resource("isovalentsrv6sidmanagers").
		Name(isovalentSRv6SIDManager.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentSRv6SIDManager).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *isovalentSRv6SIDManagers) UpdateStatus(ctx context.Context, isovalentSRv6SIDManager *v1alpha1.IsovalentSRv6SIDManager, opts v1.UpdateOptions) (result *v1alpha1.IsovalentSRv6SIDManager, err error) {
	result = &v1alpha1.IsovalentSRv6SIDManager{}
	err = c.client.Put().
		Resource("isovalentsrv6sidmanagers").
		Name(isovalentSRv6SIDManager.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentSRv6SIDManager).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentSRv6SIDManager and deletes it. Returns an error if one occurs.
func (c *isovalentSRv6SIDManagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentsrv6sidmanagers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentSRv6SIDManagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentsrv6sidmanagers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentSRv6SIDManager.
func (c *isovalentSRv6SIDManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentSRv6SIDManager, err error) {
	result = &v1alpha1.IsovalentSRv6SIDManager{}
	err = c.client.Patch(pt).
		Resource("isovalentsrv6sidmanagers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
