// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentSRv6LocatorPoolsGetter has a method to return a IsovalentSRv6LocatorPoolInterface.
// A group's client should implement this interface.
type IsovalentSRv6LocatorPoolsGetter interface {
	IsovalentSRv6LocatorPools() IsovalentSRv6LocatorPoolInterface
}

// IsovalentSRv6LocatorPoolInterface has methods to work with IsovalentSRv6LocatorPool resources.
type IsovalentSRv6LocatorPoolInterface interface {
	Create(ctx context.Context, isovalentSRv6LocatorPool *v1alpha1.IsovalentSRv6LocatorPool, opts v1.CreateOptions) (*v1alpha1.IsovalentSRv6LocatorPool, error)
	Update(ctx context.Context, isovalentSRv6LocatorPool *v1alpha1.IsovalentSRv6LocatorPool, opts v1.UpdateOptions) (*v1alpha1.IsovalentSRv6LocatorPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentSRv6LocatorPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentSRv6LocatorPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentSRv6LocatorPool, err error)
	IsovalentSRv6LocatorPoolExpansion
}

// isovalentSRv6LocatorPools implements IsovalentSRv6LocatorPoolInterface
type isovalentSRv6LocatorPools struct {
	client rest.Interface
}

// newIsovalentSRv6LocatorPools returns a IsovalentSRv6LocatorPools
func newIsovalentSRv6LocatorPools(c *IsovalentV1alpha1Client) *isovalentSRv6LocatorPools {
	return &isovalentSRv6LocatorPools{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentSRv6LocatorPool, and returns the corresponding isovalentSRv6LocatorPool object, and an error if there is any.
func (c *isovalentSRv6LocatorPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	result = &v1alpha1.IsovalentSRv6LocatorPool{}
	err = c.client.Get().
		Resource("isovalentsrv6locatorpools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentSRv6LocatorPools that match those selectors.
func (c *isovalentSRv6LocatorPools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentSRv6LocatorPoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentSRv6LocatorPoolList{}
	err = c.client.Get().
		Resource("isovalentsrv6locatorpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentSRv6LocatorPools.
func (c *isovalentSRv6LocatorPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentsrv6locatorpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentSRv6LocatorPool and creates it.  Returns the server's representation of the isovalentSRv6LocatorPool, and an error, if there is any.
func (c *isovalentSRv6LocatorPools) Create(ctx context.Context, isovalentSRv6LocatorPool *v1alpha1.IsovalentSRv6LocatorPool, opts v1.CreateOptions) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	result = &v1alpha1.IsovalentSRv6LocatorPool{}
	err = c.client.Post().
		Resource("isovalentsrv6locatorpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentSRv6LocatorPool).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentSRv6LocatorPool and updates it. Returns the server's representation of the isovalentSRv6LocatorPool, and an error, if there is any.
func (c *isovalentSRv6LocatorPools) Update(ctx context.Context, isovalentSRv6LocatorPool *v1alpha1.IsovalentSRv6LocatorPool, opts v1.UpdateOptions) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	result = &v1alpha1.IsovalentSRv6LocatorPool{}
	err = c.client.Put().
		Resource("isovalentsrv6locatorpools").
		Name(isovalentSRv6LocatorPool.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentSRv6LocatorPool).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentSRv6LocatorPool and deletes it. Returns an error if one occurs.
func (c *isovalentSRv6LocatorPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentsrv6locatorpools").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentSRv6LocatorPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentsrv6locatorpools").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentSRv6LocatorPool.
func (c *isovalentSRv6LocatorPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentSRv6LocatorPool, err error) {
	result = &v1alpha1.IsovalentSRv6LocatorPool{}
	err = c.client.Patch(pt).
		Resource("isovalentsrv6locatorpools").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
