// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentFQDNGroupsGetter has a method to return a IsovalentFQDNGroupInterface.
// A group's client should implement this interface.
type IsovalentFQDNGroupsGetter interface {
	IsovalentFQDNGroups() IsovalentFQDNGroupInterface
}

// IsovalentFQDNGroupInterface has methods to work with IsovalentFQDNGroup resources.
type IsovalentFQDNGroupInterface interface {
	Create(ctx context.Context, isovalentFQDNGroup *v1alpha1.IsovalentFQDNGroup, opts v1.CreateOptions) (*v1alpha1.IsovalentFQDNGroup, error)
	Update(ctx context.Context, isovalentFQDNGroup *v1alpha1.IsovalentFQDNGroup, opts v1.UpdateOptions) (*v1alpha1.IsovalentFQDNGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentFQDNGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentFQDNGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentFQDNGroup, err error)
	IsovalentFQDNGroupExpansion
}

// isovalentFQDNGroups implements IsovalentFQDNGroupInterface
type isovalentFQDNGroups struct {
	client rest.Interface
}

// newIsovalentFQDNGroups returns a IsovalentFQDNGroups
func newIsovalentFQDNGroups(c *IsovalentV1alpha1Client) *isovalentFQDNGroups {
	return &isovalentFQDNGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentFQDNGroup, and returns the corresponding isovalentFQDNGroup object, and an error if there is any.
func (c *isovalentFQDNGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentFQDNGroup, err error) {
	result = &v1alpha1.IsovalentFQDNGroup{}
	err = c.client.Get().
		Resource("isovalentfqdngroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentFQDNGroups that match those selectors.
func (c *isovalentFQDNGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentFQDNGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentFQDNGroupList{}
	err = c.client.Get().
		Resource("isovalentfqdngroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentFQDNGroups.
func (c *isovalentFQDNGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentfqdngroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentFQDNGroup and creates it.  Returns the server's representation of the isovalentFQDNGroup, and an error, if there is any.
func (c *isovalentFQDNGroups) Create(ctx context.Context, isovalentFQDNGroup *v1alpha1.IsovalentFQDNGroup, opts v1.CreateOptions) (result *v1alpha1.IsovalentFQDNGroup, err error) {
	result = &v1alpha1.IsovalentFQDNGroup{}
	err = c.client.Post().
		Resource("isovalentfqdngroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentFQDNGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentFQDNGroup and updates it. Returns the server's representation of the isovalentFQDNGroup, and an error, if there is any.
func (c *isovalentFQDNGroups) Update(ctx context.Context, isovalentFQDNGroup *v1alpha1.IsovalentFQDNGroup, opts v1.UpdateOptions) (result *v1alpha1.IsovalentFQDNGroup, err error) {
	result = &v1alpha1.IsovalentFQDNGroup{}
	err = c.client.Put().
		Resource("isovalentfqdngroups").
		Name(isovalentFQDNGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentFQDNGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentFQDNGroup and deletes it. Returns an error if one occurs.
func (c *isovalentFQDNGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentfqdngroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentFQDNGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentfqdngroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentFQDNGroup.
func (c *isovalentFQDNGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentFQDNGroup, err error) {
	result = &v1alpha1.IsovalentFQDNGroup{}
	err = c.client.Patch(pt).
		Resource("isovalentfqdngroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
