//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressGroup) DeepCopyInto(out *EgressGroup) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressGroup.
func (in *EgressGroup) DeepCopy() *EgressGroup {
	if in == nil {
		return nil
	}
	out := new(EgressGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRule) DeepCopyInto(out *EgressRule) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRule.
func (in *EgressRule) DeepCopy() *EgressRule {
	if in == nil {
		return nil
	}
	out := new(EgressRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsovalentEgressGatewayPolicy) DeepCopyInto(out *IsovalentEgressGatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsovalentEgressGatewayPolicy.
func (in *IsovalentEgressGatewayPolicy) DeepCopy() *IsovalentEgressGatewayPolicy {
	if in == nil {
		return nil
	}
	out := new(IsovalentEgressGatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IsovalentEgressGatewayPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsovalentEgressGatewayPolicyGroupStatus) DeepCopyInto(out *IsovalentEgressGatewayPolicyGroupStatus) {
	*out = *in
	if in.ActiveGatewayIPs != nil {
		in, out := &in.ActiveGatewayIPs, &out.ActiveGatewayIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthyGatewayIPs != nil {
		in, out := &in.HealthyGatewayIPs, &out.HealthyGatewayIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsovalentEgressGatewayPolicyGroupStatus.
func (in *IsovalentEgressGatewayPolicyGroupStatus) DeepCopy() *IsovalentEgressGatewayPolicyGroupStatus {
	if in == nil {
		return nil
	}
	out := new(IsovalentEgressGatewayPolicyGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsovalentEgressGatewayPolicyList) DeepCopyInto(out *IsovalentEgressGatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IsovalentEgressGatewayPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsovalentEgressGatewayPolicyList.
func (in *IsovalentEgressGatewayPolicyList) DeepCopy() *IsovalentEgressGatewayPolicyList {
	if in == nil {
		return nil
	}
	out := new(IsovalentEgressGatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IsovalentEgressGatewayPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsovalentEgressGatewayPolicySpec) DeepCopyInto(out *IsovalentEgressGatewayPolicySpec) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]EgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DestinationCIDRs != nil {
		in, out := &in.DestinationCIDRs, &out.DestinationCIDRs
		*out = make([]IPv4CIDR, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedCIDRs != nil {
		in, out := &in.ExcludedCIDRs, &out.ExcludedCIDRs
		*out = make([]IPv4CIDR, len(*in))
		copy(*out, *in)
	}
	if in.EgressGroups != nil {
		in, out := &in.EgressGroups, &out.EgressGroups
		*out = make([]EgressGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsovalentEgressGatewayPolicySpec.
func (in *IsovalentEgressGatewayPolicySpec) DeepCopy() *IsovalentEgressGatewayPolicySpec {
	if in == nil {
		return nil
	}
	out := new(IsovalentEgressGatewayPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsovalentEgressGatewayPolicyStatus) DeepCopyInto(out *IsovalentEgressGatewayPolicyStatus) {
	*out = *in
	if in.GroupStatuses != nil {
		in, out := &in.GroupStatuses, &out.GroupStatuses
		*out = make([]IsovalentEgressGatewayPolicyGroupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsovalentEgressGatewayPolicyStatus.
func (in *IsovalentEgressGatewayPolicyStatus) DeepCopy() *IsovalentEgressGatewayPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(IsovalentEgressGatewayPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
