// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CiliumSRv6VRFsGetter has a method to return a CiliumSRv6VRFInterface.
// A group's client should implement this interface.
type CiliumSRv6VRFsGetter interface {
	CiliumSRv6VRFs() CiliumSRv6VRFInterface
}

// CiliumSRv6VRFInterface has methods to work with CiliumSRv6VRF resources.
type CiliumSRv6VRFInterface interface {
	Create(ctx context.Context, ciliumSRv6VRF *v2alpha1.CiliumSRv6VRF, opts v1.CreateOptions) (*v2alpha1.CiliumSRv6VRF, error)
	Update(ctx context.Context, ciliumSRv6VRF *v2alpha1.CiliumSRv6VRF, opts v1.UpdateOptions) (*v2alpha1.CiliumSRv6VRF, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.CiliumSRv6VRF, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.CiliumSRv6VRFList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumSRv6VRF, err error)
	CiliumSRv6VRFExpansion
}

// ciliumSRv6VRFs implements CiliumSRv6VRFInterface
type ciliumSRv6VRFs struct {
	client rest.Interface
}

// newCiliumSRv6VRFs returns a CiliumSRv6VRFs
func newCiliumSRv6VRFs(c *CiliumV2alpha1Client) *ciliumSRv6VRFs {
	return &ciliumSRv6VRFs{
		client: c.RESTClient(),
	}
}

// Get takes name of the ciliumSRv6VRF, and returns the corresponding ciliumSRv6VRF object, and an error if there is any.
func (c *ciliumSRv6VRFs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumSRv6VRF, err error) {
	result = &v2alpha1.CiliumSRv6VRF{}
	err = c.client.Get().
		Resource("ciliumsrv6vrfs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CiliumSRv6VRFs that match those selectors.
func (c *ciliumSRv6VRFs) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumSRv6VRFList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.CiliumSRv6VRFList{}
	err = c.client.Get().
		Resource("ciliumsrv6vrfs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ciliumSRv6VRFs.
func (c *ciliumSRv6VRFs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("ciliumsrv6vrfs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a ciliumSRv6VRF and creates it.  Returns the server's representation of the ciliumSRv6VRF, and an error, if there is any.
func (c *ciliumSRv6VRFs) Create(ctx context.Context, ciliumSRv6VRF *v2alpha1.CiliumSRv6VRF, opts v1.CreateOptions) (result *v2alpha1.CiliumSRv6VRF, err error) {
	result = &v2alpha1.CiliumSRv6VRF{}
	err = c.client.Post().
		Resource("ciliumsrv6vrfs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumSRv6VRF).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a ciliumSRv6VRF and updates it. Returns the server's representation of the ciliumSRv6VRF, and an error, if there is any.
func (c *ciliumSRv6VRFs) Update(ctx context.Context, ciliumSRv6VRF *v2alpha1.CiliumSRv6VRF, opts v1.UpdateOptions) (result *v2alpha1.CiliumSRv6VRF, err error) {
	result = &v2alpha1.CiliumSRv6VRF{}
	err = c.client.Put().
		Resource("ciliumsrv6vrfs").
		Name(ciliumSRv6VRF.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumSRv6VRF).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the ciliumSRv6VRF and deletes it. Returns an error if one occurs.
func (c *ciliumSRv6VRFs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("ciliumsrv6vrfs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ciliumSRv6VRFs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("ciliumsrv6vrfs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched ciliumSRv6VRF.
func (c *ciliumSRv6VRFs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumSRv6VRF, err error) {
	result = &v2alpha1.CiliumSRv6VRF{}
	err = c.client.Patch(pt).
		Resource("ciliumsrv6vrfs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
