// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/client/listers/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentSRv6SIDManagerInformer provides access to a shared informer and lister for
// IsovalentSRv6SIDManagers.
type IsovalentSRv6SIDManagerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IsovalentSRv6SIDManagerLister
}

type isovalentSRv6SIDManagerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewIsovalentSRv6SIDManagerInformer constructs a new informer for IsovalentSRv6SIDManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIsovalentSRv6SIDManagerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIsovalentSRv6SIDManagerInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredIsovalentSRv6SIDManagerInformer constructs a new informer for IsovalentSRv6SIDManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIsovalentSRv6SIDManagerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1alpha1().IsovalentSRv6SIDManagers().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1alpha1().IsovalentSRv6SIDManagers().Watch(context.TODO(), options)
			},
		},
		&isovalentcomv1alpha1.IsovalentSRv6SIDManager{},
		resyncPeriod,
		indexers,
	)
}

func (f *isovalentSRv6SIDManagerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIsovalentSRv6SIDManagerInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *isovalentSRv6SIDManagerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&isovalentcomv1alpha1.IsovalentSRv6SIDManager{}, f.defaultInformer)
}

func (f *isovalentSRv6SIDManagerInformer) Lister() v1alpha1.IsovalentSRv6SIDManagerLister {
	return v1alpha1.NewIsovalentSRv6SIDManagerLister(f.Informer().GetIndexer())
}
