// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/client/listers/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentSRv6LocatorPoolInformer provides access to a shared informer and lister for
// IsovalentSRv6LocatorPools.
type IsovalentSRv6LocatorPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IsovalentSRv6LocatorPoolLister
}

type isovalentSRv6LocatorPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewIsovalentSRv6LocatorPoolInformer constructs a new informer for IsovalentSRv6LocatorPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIsovalentSRv6LocatorPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIsovalentSRv6LocatorPoolInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredIsovalentSRv6LocatorPoolInformer constructs a new informer for IsovalentSRv6LocatorPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIsovalentSRv6LocatorPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1alpha1().IsovalentSRv6LocatorPools().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1alpha1().IsovalentSRv6LocatorPools().Watch(context.TODO(), options)
			},
		},
		&isovalentcomv1alpha1.IsovalentSRv6LocatorPool{},
		resyncPeriod,
		indexers,
	)
}

func (f *isovalentSRv6LocatorPoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIsovalentSRv6LocatorPoolInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *isovalentSRv6LocatorPoolInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&isovalentcomv1alpha1.IsovalentSRv6LocatorPool{}, f.defaultInformer)
}

func (f *isovalentSRv6LocatorPoolInformer) Lister() v1alpha1.IsovalentSRv6LocatorPoolLister {
	return v1alpha1.NewIsovalentSRv6LocatorPoolLister(f.Informer().GetIndexer())
}
