// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CiliumSRv6VRFLister helps list CiliumSRv6VRFs.
// All objects returned here must be treated as read-only.
type CiliumSRv6VRFLister interface {
	// List lists all CiliumSRv6VRFs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumSRv6VRF, err error)
	// Get retrieves the CiliumSRv6VRF from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.CiliumSRv6VRF, error)
	CiliumSRv6VRFListerExpansion
}

// ciliumSRv6VRFLister implements the CiliumSRv6VRFLister interface.
type ciliumSRv6VRFLister struct {
	indexer cache.Indexer
}

// NewCiliumSRv6VRFLister returns a new CiliumSRv6VRFLister.
func NewCiliumSRv6VRFLister(indexer cache.Indexer) CiliumSRv6VRFLister {
	return &ciliumSRv6VRFLister{indexer: indexer}
}

// List lists all CiliumSRv6VRFs in the indexer.
func (s *ciliumSRv6VRFLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumSRv6VRF, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumSRv6VRF))
	})
	return ret, err
}

// Get retrieves the CiliumSRv6VRF from the index for a given name.
func (s *ciliumSRv6VRFLister) Get(name string) (*v2alpha1.CiliumSRv6VRF, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("ciliumsrv6vrf"), name)
	}
	return obj.(*v2alpha1.CiliumSRv6VRF), nil
}
