// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CiliumSRv6EgressPolicyLister helps list CiliumSRv6EgressPolicies.
// All objects returned here must be treated as read-only.
type CiliumSRv6EgressPolicyLister interface {
	// List lists all CiliumSRv6EgressPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumSRv6EgressPolicy, err error)
	// Get retrieves the CiliumSRv6EgressPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.CiliumSRv6EgressPolicy, error)
	CiliumSRv6EgressPolicyListerExpansion
}

// ciliumSRv6EgressPolicyLister implements the CiliumSRv6EgressPolicyLister interface.
type ciliumSRv6EgressPolicyLister struct {
	indexer cache.Indexer
}

// NewCiliumSRv6EgressPolicyLister returns a new CiliumSRv6EgressPolicyLister.
func NewCiliumSRv6EgressPolicyLister(indexer cache.Indexer) CiliumSRv6EgressPolicyLister {
	return &ciliumSRv6EgressPolicyLister{indexer: indexer}
}

// List lists all CiliumSRv6EgressPolicies in the indexer.
func (s *ciliumSRv6EgressPolicyLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumSRv6EgressPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumSRv6EgressPolicy))
	})
	return ret, err
}

// Get retrieves the CiliumSRv6EgressPolicy from the index for a given name.
func (s *ciliumSRv6EgressPolicyLister) Get(name string) (*v2alpha1.CiliumSRv6EgressPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("ciliumsrv6egresspolicy"), name)
	}
	return obj.(*v2alpha1.CiliumSRv6EgressPolicy), nil
}
