// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

// CiliumBGPPeeringPolicyListerExpansion allows custom methods to be added to
// CiliumBGPPeeringPolicyLister.
type CiliumBGPPeeringPolicyListerExpansion interface{}

// CiliumCIDRGroupListerExpansion allows custom methods to be added to
// CiliumCIDRGroupLister.
type CiliumCIDRGroupListerExpansion interface{}

// CiliumEndpointSliceListerExpansion allows custom methods to be added to
// CiliumEndpointSliceLister.
type CiliumEndpointSliceListerExpansion interface{}

// CiliumL2AnnouncementPolicyListerExpansion allows custom methods to be added to
// CiliumL2AnnouncementPolicyLister.
type CiliumL2AnnouncementPolicyListerExpansion interface{}

// CiliumLoadBalancerIPPoolListerExpansion allows custom methods to be added to
// CiliumLoadBalancerIPPoolLister.
type CiliumLoadBalancerIPPoolListerExpansion interface{}

// CiliumNodeConfigListerExpansion allows custom methods to be added to
// CiliumNodeConfigLister.
type CiliumNodeConfigListerExpansion interface{}

// CiliumNodeConfigNamespaceListerExpansion allows custom methods to be added to
// CiliumNodeConfigNamespaceLister.
type CiliumNodeConfigNamespaceListerExpansion interface{}

// CiliumPodIPPoolListerExpansion allows custom methods to be added to
// CiliumPodIPPoolLister.
type CiliumPodIPPoolListerExpansion interface{}

// CiliumSRv6EgressPolicyListerExpansion allows custom methods to be added to
// CiliumSRv6EgressPolicyLister.
type CiliumSRv6EgressPolicyListerExpansion interface{}

// CiliumSRv6VRFListerExpansion allows custom methods to be added to
// CiliumSRv6VRFLister.
type CiliumSRv6VRFListerExpansion interface{}
