// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentEgressGatewayPoliciesGetter has a method to return a IsovalentEgressGatewayPolicyInterface.
// A group's client should implement this interface.
type IsovalentEgressGatewayPoliciesGetter interface {
	IsovalentEgressGatewayPolicies() IsovalentEgressGatewayPolicyInterface
}

// IsovalentEgressGatewayPolicyInterface has methods to work with IsovalentEgressGatewayPolicy resources.
type IsovalentEgressGatewayPolicyInterface interface {
	Create(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.CreateOptions) (*v1.IsovalentEgressGatewayPolicy, error)
	Update(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.UpdateOptions) (*v1.IsovalentEgressGatewayPolicy, error)
	UpdateStatus(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.UpdateOptions) (*v1.IsovalentEgressGatewayPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.IsovalentEgressGatewayPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.IsovalentEgressGatewayPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.IsovalentEgressGatewayPolicy, err error)
	IsovalentEgressGatewayPolicyExpansion
}

// isovalentEgressGatewayPolicies implements IsovalentEgressGatewayPolicyInterface
type isovalentEgressGatewayPolicies struct {
	client rest.Interface
}

// newIsovalentEgressGatewayPolicies returns a IsovalentEgressGatewayPolicies
func newIsovalentEgressGatewayPolicies(c *IsovalentV1Client) *isovalentEgressGatewayPolicies {
	return &isovalentEgressGatewayPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentEgressGatewayPolicy, and returns the corresponding isovalentEgressGatewayPolicy object, and an error if there is any.
func (c *isovalentEgressGatewayPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	result = &v1.IsovalentEgressGatewayPolicy{}
	err = c.client.Get().
		Resource("isovalentegressgatewaypolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentEgressGatewayPolicies that match those selectors.
func (c *isovalentEgressGatewayPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.IsovalentEgressGatewayPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.IsovalentEgressGatewayPolicyList{}
	err = c.client.Get().
		Resource("isovalentegressgatewaypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentEgressGatewayPolicies.
func (c *isovalentEgressGatewayPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentegressgatewaypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentEgressGatewayPolicy and creates it.  Returns the server's representation of the isovalentEgressGatewayPolicy, and an error, if there is any.
func (c *isovalentEgressGatewayPolicies) Create(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.CreateOptions) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	result = &v1.IsovalentEgressGatewayPolicy{}
	err = c.client.Post().
		Resource("isovalentegressgatewaypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentEgressGatewayPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentEgressGatewayPolicy and updates it. Returns the server's representation of the isovalentEgressGatewayPolicy, and an error, if there is any.
func (c *isovalentEgressGatewayPolicies) Update(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.UpdateOptions) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	result = &v1.IsovalentEgressGatewayPolicy{}
	err = c.client.Put().
		Resource("isovalentegressgatewaypolicies").
		Name(isovalentEgressGatewayPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentEgressGatewayPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *isovalentEgressGatewayPolicies) UpdateStatus(ctx context.Context, isovalentEgressGatewayPolicy *v1.IsovalentEgressGatewayPolicy, opts metav1.UpdateOptions) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	result = &v1.IsovalentEgressGatewayPolicy{}
	err = c.client.Put().
		Resource("isovalentegressgatewaypolicies").
		Name(isovalentEgressGatewayPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentEgressGatewayPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentEgressGatewayPolicy and deletes it. Returns an error if one occurs.
func (c *isovalentEgressGatewayPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentegressgatewaypolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentEgressGatewayPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentegressgatewaypolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentEgressGatewayPolicy.
func (c *isovalentEgressGatewayPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.IsovalentEgressGatewayPolicy, err error) {
	result = &v1.IsovalentEgressGatewayPolicy{}
	err = c.client.Patch(pt).
		Resource("isovalentegressgatewaypolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
