// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IsovalentFQDNGroupListerExpansion allows custom methods to be added to
// IsovalentFQDNGroupLister.
type IsovalentFQDNGroupListerExpansion interface{}

// IsovalentPodNetworkListerExpansion allows custom methods to be added to
// IsovalentPodNetworkLister.
type IsovalentPodNetworkListerExpansion interface{}

// IsovalentSRv6SIDManagerListerExpansion allows custom methods to be added to
// IsovalentSRv6SIDManagerLister.
type IsovalentSRv6SIDManagerListerExpansion interface{}
