// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentPodNetworkLister helps list IsovalentPodNetworks.
// All objects returned here must be treated as read-only.
type IsovalentPodNetworkLister interface {
	// List lists all IsovalentPodNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentPodNetwork, err error)
	// Get retrieves the IsovalentPodNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentPodNetwork, error)
	IsovalentPodNetworkListerExpansion
}

// isovalentPodNetworkLister implements the IsovalentPodNetworkLister interface.
type isovalentPodNetworkLister struct {
	indexer cache.Indexer
}

// NewIsovalentPodNetworkLister returns a new IsovalentPodNetworkLister.
func NewIsovalentPodNetworkLister(indexer cache.Indexer) IsovalentPodNetworkLister {
	return &isovalentPodNetworkLister{indexer: indexer}
}

// List lists all IsovalentPodNetworks in the indexer.
func (s *isovalentPodNetworkLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentPodNetwork, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentPodNetwork))
	})
	return ret, err
}

// Get retrieves the IsovalentPodNetwork from the index for a given name.
func (s *isovalentPodNetworkLister) Get(name string) (*v1alpha1.IsovalentPodNetwork, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentpodnetwork"), name)
	}
	return obj.(*v1alpha1.IsovalentPodNetwork), nil
}
