apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: cegp-sample-excluded-cidrs
spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: cilium-test
        kind: client
  destinationCIDRs:
  - 0.0.0.0/0
  excludedCIDRs:
  - NODE_WITHOUT_CILIUM_PLACEHOLDER/32
  egressGroups:
  - nodeSelector:
      matchLabels:
        kubernetes.io/hostname: NODE_NAME_PLACEHOLDER
