// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package policy

import (
	"github.com/google/uuid"
	k8sTypes "k8s.io/apimachinery/pkg/types"

	"github.com/cilium/cilium/pkg/labels"
	"github.com/cilium/cilium/pkg/lock"
	"github.com/cilium/cilium/pkg/logging"
	"github.com/cilium/cilium/pkg/logging/logfields"
	"github.com/cilium/cilium/pkg/metrics"
)

var (
	log          = logging.DefaultLogger.WithField(logfields.LogSubsys, "policy")
	mutex        lock.RWMutex // Protects enablePolicy
	enablePolicy string       // Whether policy enforcement is enabled.

	uuidForPolicyAPI = k8sTypes.UID(uuid.New().String())
)

// SetPolicyEnabled sets the policy enablement configuration. Valid values are:
// - endpoint.AlwaysEnforce
// - endpoint.NeverEnforce
// - endpoint.DefaultEnforcement
func SetPolicyEnabled(val string) {
	mutex.Lock()
	enablePolicy = val
	mutex.Unlock()
}

// GetPolicyEnabled returns the policy enablement configuration
func GetPolicyEnabled() string {
	mutex.RLock()
	val := enablePolicy
	mutex.RUnlock()
	return val
}

// AddOptions are options which can be passed to PolicyAdd
type AddOptions struct {
	// Replace if true indicates that existing rules with identical labels should be replaced
	Replace bool
	// ReplaceWithLabels if present indicates that existing rules with the
	// given LabelArray should be deleted.
	ReplaceWithLabels labels.LabelArray
	// Generated should be set as true to signalize a the policy being inserted
	// was generated by cilium-agent, e.g. dns poller.
	Generated bool

	// The source of this policy, one of api, fqdn or k8s
	Source string

	// UID is a unique identifier for the resource that added the policy.
	UID k8sTypes.UID
}

func (a *AddOptions) GetUID() k8sTypes.UID {
	if a != nil {
		// IPCache relies on consistent UID for insert, delete
		// operations
		if a.Source == metrics.LabelEventSourceAPI {
			return uuidForPolicyAPI
		}
		return a.UID
	}
	return ""
}

// DeleteOptions are options which can be passed to PolicyAdd
type DeleteOptions struct {
	// The source of this policy, one of api, fqdn or k8s
	Source string

	// UID is a unique identifier for the resource that added the policy.
	UID k8sTypes.UID
}

func (a *DeleteOptions) GetUID() k8sTypes.UID {
	if a != nil {
		// IPCache relies on consistent UID for insert, delete
		// operations
		if a.Source == metrics.LabelEventSourceAPI {
			return uuidForPolicyAPI
		}
		return a.UID
	}
	return ""
}
