name: Set environment variables
description: Set environment variables
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "QUAY_ORGANIZATION=isovalent" >> $GITHUB_ENV
        echo "QUAY_ORGANIZATION_DEV=isovalent-dev" >> $GITHUB_ENV
        # no prod yet
        echo "QUAY_CHARTS_ORGANIZATION_DEV=isovalent-charts-dev" >> $GITHUB_ENV
        echo "BRANCH_SUFFIX=-ce" >> $GITHUB_ENV
        # renovate: datasource=github-releases depName=cilium/cilium-cli
        CILIUM_CLI_VERSION="v0.15.14"
        echo "CILIUM_CLI_VERSION=$CILIUM_CLI_VERSION" >> $GITHUB_ENV
