name: Set environment variables
description: Set environment variables
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "QUAY_ORGANIZATION=isovalent" >> $GITHUB_ENV
        echo "QUAY_ORGANIZATION_DEV=isovalent-dev" >> $GITHUB_ENV
