// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/cilium/cilium/pkg/k8s/client/listers/isovalent.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentEgressGatewayPolicyInformer provides access to a shared informer and lister for
// IsovalentEgressGatewayPolicies.
type IsovalentEgressGatewayPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.IsovalentEgressGatewayPolicyLister
}

type isovalentEgressGatewayPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewIsovalentEgressGatewayPolicyInformer constructs a new informer for IsovalentEgressGatewayPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIsovalentEgressGatewayPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIsovalentEgressGatewayPolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredIsovalentEgressGatewayPolicyInformer constructs a new informer for IsovalentEgressGatewayPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIsovalentEgressGatewayPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1().IsovalentEgressGatewayPolicies().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1().IsovalentEgressGatewayPolicies().Watch(context.TODO(), options)
			},
		},
		&isovalentcomv1.IsovalentEgressGatewayPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *isovalentEgressGatewayPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIsovalentEgressGatewayPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *isovalentEgressGatewayPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&isovalentcomv1.IsovalentEgressGatewayPolicy{}, f.defaultInformer)
}

func (f *isovalentEgressGatewayPolicyInformer) Lister() v1.IsovalentEgressGatewayPolicyLister {
	return v1.NewIsovalentEgressGatewayPolicyLister(f.Informer().GetIndexer())
}
