name: atlantis-gen
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to checkout and run atlantis gen on (e.g. v1.10.3-cee.1).
        default: ""
        required: true
jobs:
  atlantis-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Download atlantis
      uses: dsaltares/fetch-gh-release-asset@0.0.8
      with:
        repo: "isovalent/atlantis"
        version: "tags/v1.0.0-alpha4.4"
        file: "atlantis-.*-linux-amd64.tar.gz"
        regex: true
        token: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}

    - name: Download atlantis checksum file
      uses: dsaltares/fetch-gh-release-asset@0.0.8
      with:
        repo: "isovalent/atlantis"
        version: "tags/v1.0.0-alpha4.4"
        file: "atlantis-.*-linux-amd64.tar.gz.sha256sum"
        regex: true
        token: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}

    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Run atlantis gen
      shell: bash
      run: |
        sha256sum --check atlantis-*-linux-amd64.tar.gz.sha256sum
        tar xf atlantis-*-linux-amd64.tar.gz
        mv atlantis /usr/local/bin
        # Atlantis needs to access private repos.
        git config --global url."https://${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}:@github.com/".insteadOf "https://github.com/"
        git config --global --add url."https://${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}:@github.com/".insteadOf "git@github.com:"
        atlantis version
        atlantis gen
        git status

    - name: Push
      shell: bash
      run: |
        git config user.name "isovalent-bot"
        git config user.email "<>"
        git add go.mod go.sum api daemon vendor
        if git diff --cached --exit-code > /dev/null ; then
            echo "Nothing to commit"
        else
            git commit -m "Run atlantis gen on ${{ github.event.inputs.tag }}"
            git checkout -b ${{ github.event.inputs.tag }}-gen
            git push origin ${{ github.event.inputs.tag }}-gen
            git tag -a "${{ github.event.inputs.tag }}-gen-tag" -m "${{ github.event.inputs.tag }}-gen-tag"
            git push origin ${{ github.event.inputs.tag }}-gen-tag
        fi
