name: Enterprise Multi-Network (ci-multi-network)

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: true
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: '{}'
  # Run every 6 hours
  schedule:
    - cron: '0 1/6 * * *'

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To allow retrieving information from the PR API
  pull-requests: read
  # To be able to set commit status
  statuses: write

concurrency:
  # Structure:
  # - Workflow name
  # - Event type
  # - A unique identifier depending on event type:
  #   - schedule: SHA
  #   - workflow_dispatch: PR number
  #
  # This structure ensures a unique concurrency group name is generated for each
  # type of testing, such that re-runs will cancel the previous run.
  group: |
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{
      (github.event_name == 'schedule' && github.sha) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.PR-number)
    }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=cilium/cilium-cli
  cilium_cli_version: v0.15.8
  network-definitions: enterprise/examples/kubernetes/multi-network/isovalentpodnetworks.yaml

jobs:
  commit-status-start:
    runs-on: ubuntu-latest
    steps:
      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@243b4f7e597f62335408d58001edf8a02cf3e1fd # v1.1.7
        with:
          sha: ${{ inputs.SHA || github.sha }}

  enterprise-multi-network-conformance-test:
    runs-on: ubuntu-latest-4cores-16gb
    env:
      job_name: 'Setup & Test'
    timeout-minutes: 120
    steps:
      - name: Checkout context ref (trusted)
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ inputs.context-ref || github.sha }}
          persist-credentials: false

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SHA="${{ inputs.SHA }}"
            CONTEXT_REF="${{ inputs.context-ref }}"
            OWNER="${{ inputs.PR-number }}"
          else
            SHA="${{ github.sha }}"
            CONTEXT_REF="${{ github.sha }}"
            OWNER="${{ github.ref_name }}"
            OWNER="${OWNER/./-}"
          fi

          echo sha=${SHA} >> $GITHUB_OUTPUT
          echo context-ref=${CONTEXT_REF} >> $GITHUB_OUTPUT
          echo owner=${OWNER} >> $GITHUB_OUTPUT

          # Notes:
          #  - Multi-network only supports direct routing, thus we disable
          #    tunnel mode and enable auto-direct-routes.
          #  - Multi-network only supports endpoint routes, thus we disable
          #    the local-node-route.
          #  - iptables-based masquerading does not support multiple non-masquerade
          #    CIDRs. Thus, we enable BPF masquerading where we can add multiple
          #    non-masquerade CIDRs.
          CILIUM_INSTALL_DEFAULTS="--chart-directory=install/kubernetes/cilium \
            --helm-set=debug.enabled=true \
            --helm-set=debug.verbose=envoy \
            --helm-set=image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-ci \
            --helm-set=image.useDigest=false \
            --helm-set=image.tag=${SHA} \
            --helm-set=operator.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/operator \
            --helm-set=operator.image.suffix=-ci \
            --helm-set=operator.image.tag=${SHA} \
            --helm-set=operator.image.useDigest=false \
            --helm-set=hubble.relay.enabled=true \
            --helm-set=hubble.relay.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci \
            --helm-set=hubble.relay.image.tag=${SHA} \
            --helm-set=hubble.relay.image.useDigest=false \
            --helm-set=tunnel=disabled \
            --helm-set=routingMode=native \
            --helm-set=autoDirectNodeRoutes=true \
            --helm-set=endpointRoutes.enabled=true \
            --helm-set-string=extraConfig.enable-local-node-route=false \
            --helm-set=kubeProxyReplacement=strict \
            --helm-set=bpf.masquerade=true \
            --helm-set=bpf.hostLegacyRouting=true \
            --helm-set=ipv4NativeRoutingCIDR=10.0.0.0/8 \
            --helm-set=ipMasqAgent.enabled=true \
            --helm-set=ipMasqAgent.config.nonMasqueradeCIDRs='{192.168.0.0/16}' \
            --helm-set=ipam.mode=multi-pool \
            --helm-set=ipam.operator.autoCreateCiliumPodIPPools.default.ipv4.cidrs='{10.10.0.0/16}' \
            --helm-set=ipam.operator.autoCreateCiliumPodIPPools.default.ipv4.maskSize=24 \
            --helm-set=ipam.operator.autoCreateCiliumPodIPPools.secondary-pool.ipv4.cidrs='{192.168.16.0/20}' \
            --helm-set=ipam.operator.autoCreateCiliumPodIPPools.secondary-pool.ipv4.maskSize=27 \
            --helm-set=enterprise.multiNetwork.enabled=true \
            --helm-set=enterprise.multiNetwork.autoCreateDefaultPodNetwork=true"

          CONNECTIVITY_TEST_DEFAULTS="--flow-validation=disabled --hubble=false --collect-sysdump-on-failure \
            --deployment-pod-annotations='{ \
              \"*\":{\"network.v1alpha1.isovalent.com/pod-networks\":\"default,secondary-network\"}, \
              \"echo-other-node\":{\"network.v1alpha1.isovalent.com/pod-networks\":\"secondary-network\"}, \
              \"client2\":{\"network.v1alpha1.isovalent.com/pod-networks\":\"secondary-network\"} \
            }'"

          echo cilium_install_defaults=${CILIUM_INSTALL_DEFAULTS} >> $GITHUB_OUTPUT
          echo connectivity_test_defaults=${CONNECTIVITY_TEST_DEFAULTS} >> $GITHUB_OUTPUT

      # Warning: since this is a privileged workflow, subsequent workflow job
      # steps must take care not to execute untrusted code.
      - name: Checkout pull request branch (NOT TRUSTED)
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ steps.vars.outputs.sha }}
          persist-credentials: false

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@7f33713a0710a1fff76cfe1b7fd7fbaea2ce7977 # v0.15.8
        with:
          release-version: ${{ env.cilium_cli_version }}
          ci-version: ${{ env.cilium_cli_ci_version }}
          binary-name: cilium-cli
          binary-dir: ./

      - name: Provision LVH VMs
        uses: cilium/little-vm-helper@908ab1ff8a596a03cd5221a1f8602dc44c3f906d # v0.0.12
        with:
          test-name: enterprise-multi-network
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          image-version: '6.0-20230420.212204'
          host-mount: ./
          cpu: 4
          dns-resolver: '1.1.1.1'
          install-dependencies: 'true'
          cmd: |
            git config --global --add safe.directory /host

      - name: Wait for images to be available
        timeout-minutes: 30
        shell: bash
        run: |
          for image in cilium-ci operator-generic-ci hubble-relay-ci; do
            until docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/$image:${{ steps.vars.outputs.sha }} &> /dev/null; do sleep 45s; done
          done

      - name: Run connectivity tests
        uses: cilium/little-vm-helper@908ab1ff8a596a03cd5221a1f8602dc44c3f906d # v0.0.12
        with:
          provision: 'false'
          cmd: |
            cd /host/

            # create kind cluster with secondary network named "secondary-network"
            ./contrib/scripts/kind.sh --secondary-network "1" "2"

            export CILIUM_CLI_MODE=helm
            ./cilium-cli install ${{ steps.vars.outputs.cilium_install_defaults }}
            ./cilium-cli status --wait

            # Create 'secondary-network' IsovalentPodNetwork
            kubectl apply -f ${{ env.network-definitions }}

            kubectl get pods --all-namespaces -o wide
            kubectl get cep --all-namespaces -o wide
            kubectl -n kube-system exec daemonset/cilium -- cilium status
            kubectl get isovalentpodnetworks -o yaml

            # Verify that both IsovalentPodNetworks got created
            kubectl get isovalentpodnetworks -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "^default$"
            kubectl get isovalentpodnetworks -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "^secondary-network$"

            mkdir -p cilium-junits

            ./cilium-cli connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} \
              --junit-file "cilium-junits/${{ env.job_name }} - 1.xml" \
              --junit-property github_job_step="Run connectivity tests"

            kubectl get pods --all-namespaces -o wide
            kubectl get cep --all-namespaces -o wide

            # Check that endpoints got created for secondary network
            CLIENT_CEP=\$(kubectl -n cilium-test get cep -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "^client-.*-.*-cil1")
            SAME_NODE_CEP=\$(kubectl -n cilium-test get cep -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "^echo-same-node-.*-.*-cil1")

            # Check that CNI generated labels got added to identity labels of the CEPs
            kubectl -n cilium-test get cep \$CLIENT_CEP -o jsonpath='{.status.identity.labels}' | grep "cni:com.isovalent.v1alpha1.network.attachment/secondary-network=cil1"
            kubectl -n cilium-test get cep \$SAME_NODE_CEP -o jsonpath='{.status.identity.labels}' | grep "cni:com.isovalent.v1alpha1.network.attachment/secondary-network=cil1"

            CLIENT_POD=\$(kubectl -n cilium-test get pod -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "^client-.*-.*")
            SAME_NODE_POD=\$(kubectl -n cilium-test get pod -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "^echo-same-node-.*-.*")

            # Check that multi-homed pods got routes set up for secondary network
            kubectl -n cilium-test exec -ti \$CLIENT_POD -- ip route | grep "^192\.168\.0\.0/16 via 192\.168\.0\.1 dev cil1"
            kubectl -n cilium-test exec -ti \$SAME_NODE_POD -- ip route | grep "^192\.168\.0\.0/16 via 192\.168\.0\.1 dev cil1"

            ./contrib/scripts/kind-down.sh

      - name: Fetch artifacts
        if: ${{ !success() }}
        uses: cilium/little-vm-helper@908ab1ff8a596a03cd5221a1f8602dc44c3f906d # v0.0.12
        with:
          provision: 'false'
          cmd: |
            cd /host
            kubectl get pods --all-namespaces -o wide
            ./cilium-cli status
            mkdir -p cilium-sysdumps
            ./cilium-cli sysdump

      - name: Upload artifacts
        if: ${{ !success() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: cilium-sysdumps
          path: cilium-sysdump-*.zip
          retention-days: 5

      - name: Upload JUnits [junit]
        if: ${{ always() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: cilium-junits
          path: cilium-junits/*.xml
          retention-days: 2

      - name: Publish Test Results As GitHub Summary
        if: ${{ always() }}
        uses: aanm/junit2md@332ebf0fddd34e91b03a832cfafaa826306558f9 # v0.0.3
        with:
          junit-directory: "cilium-junits"

  commit-status-final:
    if: ${{ always() }}
    name: Commit Status Final
    needs: enterprise-multi-network-conformance-test
    runs-on: ubuntu-latest
    steps:
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@243b4f7e597f62335408d58001edf8a02cf3e1fd # v1.1.7
        with:
          sha: ${{ inputs.SHA || github.sha }}
          status: ${{ needs.enterprise-multi-network-conformance-test.result }}
