name: Chart CI Build

on:
  # run after the image build completes
  workflow_run:
    workflows: ["Image CI Build"]
    types:
      - completed
  # allow manually triggering it as well, for existing refs
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: 'Git ref to build. This needs to be a full commit SHA.'
        required: true

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To allow retrieving information from the PR API
  pull-requests: read
  # So that Sibz/github-status-action can write into the status API
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

env:
  check_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  push-charts:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.head_branch != '' }}
    steps:
    - name: Get triggering event ref
      id: get-ref
      run: |
        if [ "${{ inputs.checkout_ref }}" != "" ]; then
          echo ref=${{ inputs.checkout_ref }} >> $GITHUB_OUTPUT
        elif [ "${{ toJson(github.event.workflow_run.pull_requests) }}" != "[]" ]; then
          # If the workflow run was from a pull request, github.event.workflow_run.head_sha
          # is set to the commit SHA. The subsequent checkout will be in the detached HEAD
          # state, and "git rev-parse --abbrev-ref HEAD" will just print "HEAD". Set the ref
          # to pull request branch name instead so that we get the correct branch name.
          echo ref=${{ github.event.workflow_run.pull_requests[0].head.ref }} >> $GITHUB_OUTPUT
        elif [ "${{ github.event.workflow_run.head_sha }}" != "" ]; then
          echo ref=${{ github.event.workflow_run.head_sha }} >> $GITHUB_OUTPUT
        else
          echo "Invalid event type"
          exit 1
        fi

    - name: Set commit status to pending
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push in progress
        state: pending
        target_url: ${{ env.check_url }}

    - name: Get image tag
      id: get-tag
      run: |
        if [ "${{ inputs.checkout_ref }}" != "" ]; then
          echo tag=${{ inputs.checkout_ref }} >> $GITHUB_OUTPUT
        elif [ "${{ github.event.workflow_run.head_sha }}" != "" ]; then
          echo tag=${{ github.event.workflow_run.head_sha }} >> $GITHUB_OUTPUT
        else
          echo "Invalid event type"
          exit 1
        fi
    - name: Checkout Source Code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        persist-credentials: false
        ref: ${{ steps.get-ref.outputs.ref }}
        # required for git describe
        fetch-depth: 0
    - id: get-version
      run: |
        echo "chart_version=$(./contrib/scripts/print-chart-version.sh)" | tee -a $GITHUB_OUTPUT
    - name: Push charts
      uses: isovalent/reusable-workflows/.github/actions/push-helm-chart@v0.2.0
      with:
        name: cilium
        path: install/kubernetes/cilium
        version: ${{ steps.get-version.outputs.chart_version }}
        values_file_changes: |
          {

            "image.repository": "quay.io/isovalent-dev/cilium-ci",
            "image.tag": "${{ steps.get-tag.outputs.tag }}",
            "preflight.image.repository": "quay.io/isovalent-dev/cilium-ci",
            "preflight.image.tag": "${{ steps.get-tag.outputs.tag }}",
            "operator.image.repository": "quay.io/isovalent-dev/operator",
            "operator.image.suffix": "-ci",
            "operator.image.tag": "${{ steps.get-tag.outputs.tag }}",
            "hubble.relay.image.repository": "quay.io/isovalent-dev/hubble-relay-ci",
            "hubble.relay.image.tag": "${{ steps.get-tag.outputs.tag }}",
            "clustermesh.apiserver.image.repository": "quay.io/isovalent-dev/clustermesh-apiserver-ci",
            "clustermesh.apiserver.image.tag": "${{ steps.get-tag.outputs.tag }}"
          }
        registry: quay.io
        registry_namespace: isovalent-charts-dev
        registry_username: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_USERNAME }}
        registry_password: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_PASSWORD }}

    - name: Set commit status to success
      if: ${{ success() }}
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push successful
        state: success
        target_url: ${{ env.check_url }}

    - name: Set commit status to failure
      if: ${{ failure() }}
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push failed
        state: failure
        target_url: ${{ env.check_url }}

    - name: Set commit status to cancelled
      if: ${{ cancelled() }}
      uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: Helm push cancelled
        state: error
        target_url: ${{ env.check_url }}
