{{- if and .Values.operator.enabled .Values.serviceAccounts.operator.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enterprise-cilium-operator
  labels:
    app.kubernetes.io/part-of: cilium
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - update
  resourceNames:
  - isovalentegressgatewaypolicies.isovalent.com
- apiGroups:
  - isovalent.com
  resources:
  - isovalentsrv6locatorpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - isovalent.com
  resources:
  - isovalentsrv6sidmanagers
  verbs:
  - get
  - list
  - watch
{{- if or .Values.enterprise.srv6.locatorPoolEnabled }}
  - create
  - update
  - delete
  - patch
{{- end }}
{{- end }}
