{{- if and .Values.operator.enabled .Values.serviceAccounts.operator.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: enterprise-cilium-operator
  labels:
    app.kubernetes.io/part-of: cilium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enterprise-cilium-operator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccounts.operator.name | quote }}
    namespace: {{ .Release.Namespace }}
{{- end }}
